name: All push

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        compiler: [g++-12, clang++-17]
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup compiler
      run: python3 ./.github/compiler_setup.py ${{ matrix.compiler }}

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python dependencies
      run: python -m pip install numpy pytest cmake

    - name: Configure CMake
      env:
        CXX: ${{ matrix.compiler }}
      run: cmake -B ${{github.workspace}}/build -DCMAKE_CXX_COMPILER=${CXX}

    - name: Build
      # Build your program with the given configuration
      run: |
        cmake --build ${{github.workspace}}/build --verbose --parallel
        du build/tests/test_pauli_op

    - name: Test C++
      env:
        OMP_NUM_THREADS: 2
      run: |
        # ctest --test-dir build --verbose # TODO not using bc of PauliOp problems on CI
        ./build/tests/test_factory
        ./build/tests/test_pauli
        ./build/tests/test_pauli_op --test-case-exclude="*multistring*"
        ./build/tests/test_pauli_string
        ./build/tests/test_summed_pauli_op

    # - name: Test Python
      # run: PYTHONPATH=build:$PYTHONPATH pytest -v test
